language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - g++-4.9
      - lcov
      - libpoppler-cpp-dev
env: CXX=g++-4.9
node_js:
  - '6.11.1'
before_install:
  - npm i npm -g
script:
  - npm test
  - npm run lint
  - npm run coveralls
