version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    working_directory: ~/pdffonts
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install System dependencies
          command: |
            apk update --update-cache
            apk add --update git openssh-client curl docker-cli

      - run:
          name: Create docker container
          command: |
              docker build . \
              --build-arg NODE_ENV=development \
              -t 'pdffonts'
      - run:
          name: Run docker container
          command: |
              docker run \
              -t 'pdffonts' \
              --name 'pdffonts-container'
              -d
      - run:
          name: Run linter
          command: docker exec -t pdffonts-container yarn lint

      - run:
          name: Run tests
          command: docker exec -t pdffonts-container yarn test

      - run:
          name: Enforce coverage
          command: docker exec -t pdffonts-container ./scripts/enforce_coverage.sh
