version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.11.1
    working_directory: ~/pdffonts
    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            sudo sh -c 'echo "deb http://deb.debian.org/debian/ jessie main" > /etc/apt/sources.list'
            sudo sh -c 'echo "deb-src http://deb.debian.org/debian/ jessie main" >> /etc/apt/sources.list'
            sudo sh -c 'echo "deb http://security.debian.org/ jessie/updates main" >> /etc/apt/sources.list'
            sudo sh -c 'echo "deb-src http://security.debian.org/ jessie/updates main" >> /etc/apt/sources.list'
            sudo sh -c 'echo "deb http://archive.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
            sudo sh -c 'echo "deb-src http://archive.debian.org/debian jessie-backports main" >> /etc/apt/sources.list'
            sudo apt-get update -o Acquire::Check-Valid-Until=false -o Acquire::CompressionTypes::Order::=gz
            sudo apt-get install -y --no-install-recommends g++-4.9 libpoppler-private-dev poppler-data lcov

      - run:
          name: Install Node dependencies
          command: yarn

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Enforce coverage
          command: ./scripts/enforce_coverage.sh
