version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    working_directory: ~/pdffonts
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Node dependencies
          command: yarn

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Enforce coverage
          command: ./scripts/enforce_coverage.sh
